apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wizard-rpg

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - frontend-nginx-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: wizard-rpg
  app.kubernetes.io/managed-by: argocd
